#!/usr/bin/env python3
"""
DISCOVERY TIER (program §12.1) — verification of the change-of-variable
reformulation for the resource-bounded Li-barrier (Open Problem 1).
Conjecture/evidence only; NOT imported into proofs.

Claim to verify EXACTLY (rational arithmetic):

  For an orbit generated by rho = sigma + i*tau (closed under conj and 1-rho),
  set w = 1 - 1/rho and u = (w + 1/w)/2.  Then the Li-observation of the orbit
  is
        O_j(orbit)  =  8 * (1 - Re T_j(u)),        j = 1, 2, ...
  where T_j is the Chebyshev polynomial.  In particular:
   * ON-LINE  (sigma=1/2): u is REAL in [-1,1], u = (4t^2-1)/(4t^2+1) = x_t,
     and O_j = 8*(1 - T_j(u)) is BOUNDED (|O_j| <= 16).
   * OFF-LINE (sigma!=1/2): u is OUTSIDE [-1,1] (or complex off the interval),
     T_j(u) grows, O_j grows like Gamma^j, Gamma = |u + sqrt(u^2-1)| > 1.

Hence a collision (matching O_1..O_m of an on-line and an off-line multiset) is
an integer signed measure with VANISHING Chebyshev moments 0..m and at least
one off-interval support point.  The Chebyshev extremal property then gives the
archimedean lower bound   sum_online |c| >= |q*| * |T_m(u*)| >= (1/2) Gamma^m.

This script:
 (A) verifies  O_j(orbit) = 8(1 - Re T_j(u))  for on-line and off-line orbits;
 (B) rebuilds a real collision (from the LLL probe) as a vanishing-moment
     identity and checks it exactly;
 (C) checks the Chebyshev bound sum_online|c| >= |q*||T_m(u*)| on real collisions.
"""
from __future__ import annotations
from fractions import Fraction as Fr
import cmath, math
import discovery.probe_overdetermined_collision as P


# ---- exact complex-rational T_j(u) for u = ur + i*ui (Fractions) ----
def cheb_T_complex(j, ur, ui):
    """T_j(u), u = ur + i ui, exact Fraction real/imag. T_0=1,T_1=u,rec."""
    if j == 0:
        return Fr(1), Fr(0)
    a_r, a_i = Fr(1), Fr(0)          # T_0
    b_r, b_i = ur, ui                # T_1
    for _ in range(1, j):
        # T_{k+1} = 2u T_k - T_{k-1}
        two_u_Tk_r = 2 * (ur * b_r - ui * b_i)
        two_u_Tk_i = 2 * (ur * b_i + ui * b_r)
        c_r, c_i = two_u_Tk_r - a_r, two_u_Tk_i - a_i
        a_r, a_i, b_r, b_i = b_r, b_i, c_r, c_i
    return b_r, b_i


def w_and_u(sigma, tau):
    """rho = sigma + i tau (Fractions).  w = 1 - 1/rho.  u = (w + 1/w)/2.
    Returns (u_r, u_i) exact."""
    sigma, tau = Fr(sigma), Fr(tau)
    # 1/rho = conj(rho)/|rho|^2
    den = sigma * sigma + tau * tau
    inv_r, inv_i = sigma / den, -tau / den
    w_r, w_i = 1 - inv_r, -inv_i
    # 1/w
    wden = w_r * w_r + w_i * w_i
    iw_r, iw_i = w_r / wden, -w_i / wden
    u_r = (w_r + iw_r) / 2
    u_i = (w_i + iw_i) / 2
    return u_r, u_i


def O_orbit_direct(sigma, tau, m):
    """O_j of the orbit {sigma±i tau, (1-sigma)±i tau} via the phi definition
    (the same convention as the certified checker), for j=1..m."""
    sigma, tau = Fr(sigma), Fr(tau)
    atoms = [(sigma, tau), (sigma, -tau), (1 - sigma, tau), (1 - sigma, -tau)]
    out = []
    for j in range(1, m + 1):
        s = Fr(0)
        for (re, im) in atoms:
            for (r2, i2) in ((re, im), (1 - re, im)):
                s += P._phi_re(j, r2, i2)
        out.append(s)
    return out


if __name__ == "__main__":
    print("=" * 72)
    print("(A) Verify  O_j(orbit) = 8 (1 - Re T_j(u)),  u = (w+1/w)/2, w=1-1/rho")
    print("=" * 72)
    tests = [(Fr(1, 2), Fr(1)), (Fr(1, 2), Fr(3, 2)),      # on-line
             (Fr(3, 4), Fr(1)), (Fr(1, 4), Fr(2)), (Fr(5, 6), Fr(1, 2))]  # off
    m = 8
    all_ok = True
    for (sig, tau) in tests:
        u_r, u_i = w_and_u(sig, tau)
        Od = O_orbit_direct(sig, tau, m)
        ok = True
        for j in range(1, m + 1):
            Tr, Ti = cheb_T_complex(j, u_r, u_i)
            pred = 8 * (1 - Tr)          # 8(1 - Re T_j(u))
            if pred != Od[j - 1]:
                ok = False
                break
        online = (sig == Fr(1, 2))
        onl = "ON-line " if online else "OFF-line"
        uinfo = (f"u={u_r} (real, in[-1,1]:{-1 <= u_r <= 1})" if u_i == 0
                 else f"u={float(u_r):.4f}+{float(u_i):.4f}i (off interval)")
        print(f"  {onl} (sig={sig},tau={tau}): O_j==8(1-ReT_j(u)) for j=1..{m}: "
              f"{ok}   {uinfo}")
        all_ok = all_ok and ok
    print(f"\n  (A) all-match: {all_ok}")

    print("\n" + "=" * 72)
    print("(B)+(C) Rebuild a real LLL collision as a vanishing-moment identity,")
    print("        and check the Chebyshev bound  sum_online|c| >= |q*|*|T_m(u*)|.")
    print("=" * 72)

    def shortest_rel_custom(ts, dvec, m, weight_bits=24):
        vecs = [P.C_vec(t, m) for t in ts] + [dvec]
        K1 = len(vecs); Lden = 1
        for v in vecs:
            for x in v:
                Lden = Lden * x.denominator // math.gcd(Lden, x.denominator)
        Vint = [[int(x * Lden) for x in v] for v in vecs]
        w = 1 << weight_bits; basis = []
        for i in range(K1):
            row = [0] * K1 + [w * c for c in Vint[i]]; row[i] = 1; basis.append(row)
        red = P.lll(basis); best = None
        for row in red:
            c = row[:K1]; tail = row[K1:]
            if any(tail) or c[-1] == 0:
                continue
            mc = max(abs(v) for v in c)
            if best is None or mc < best[2]:
                best = (c[:-1], c[-1], mc)
        return best

    sig, tau = Fr(3, 4), Fr(1)
    u_r, u_i = w_and_u(sig, tau)                     # off-line u*
    Gamma = abs(complex(float(u_r), float(u_i)) +
                cmath.sqrt(complex(float(u_r), float(u_i))**2 - 1))
    Gamma = max(Gamma, 1 / Gamma)                    # rate = the >1 branch
    print(f"off-line u* = {float(u_r):.4f}+{float(u_i):.4f}i,  Gamma = {Gamma:.4f}")
    print(f"{'m':>3} | {'sum_online|c|':>16} | {'|q*|':>10} | "
          f"{'|T_m(u*)|':>14} | {'bound |q*||T_m|':>16} | {'holds?':>6}")
    for mm in range(2, 8):
        K = mm + 5
        ts = [Fr(1, 2) + Fr(i) for i in range(K)]
        best = shortest_rel_custom(ts, O_orbit_direct(sig, tau, mm), mm)
        if best is None:
            print(f"{mm}: none"); continue
        nc, q, mc = best
        sum_online = sum(abs(x) for x in nc)
        Tr, Ti = cheb_T_complex(mm, u_r, u_i)
        Tm = abs(complex(float(Tr), float(Ti)))
        bound = abs(q) * Tm
        holds = sum_online >= bound - 1e-6
        print(f"{mm:>3} | {sum_online:>16} | {abs(q):>10} | {Tm:>14.3f} | "
              f"{bound:>16.3f} | {str(holds):>6}")
    print("\n  If 'holds' is True throughout: the Chebyshev archimedean bound")
    print("  sum_online|c| >= |q*||T_m(u*)| >= (1/2)Gamma^m is confirmed on real")
    print("  collisions => the archimedean channel is rigorous.")
